version: 2.0.{build}
skip_tags: true
image: Visual Studio 2022

artifacts:
  - path: artifacts/seqfwd-*.zip
  - path: artifacts/seqfwd-*.tar.gz

build_script:
  - ps: ./Build.ps1 -shortver "$($env:APPVEYOR_BUILD_VERSION)"

deploy:
  - provider: GitHub
    auth_token:
      secure: Bo3ypKpKFxinjR9ShkNekNvkob2iklHJU+UlYyfHtcFFIAa58SV2TkEd0xWxz633
    artifact: /seqfwd-.*\.(zip|tar\.gz)/
    tag: v$(appveyor_build_version)
    on:
      branch: main
  